### PR TITLE
Tg4 613

### PR DESCRIPTION
**Pull request by AdvancedResearchConsulting**

### CODE REVIEW

**Comment by AdvancedResearchConsulting** [comment]
Update to support TG4 hardware, not this should probably stay as a branch as the changes aren't backwards compatible w/ the TG3B hardware

**Comment by nicost** [comment]
Sorry for the delay Austin.  I think it would be much nicer to move the V3 firmware to a directory named "TriggerScope-V3" and the V4 firmware to a directory name "TriggerScope-V4" or similar.  Branches are not meant to contain different content to be distributed, they are allowing you to develop for a while independent of the main branch, but the goal is to eventually merge it back into the main branch.  Also much nicer for visitors to see both firmware versions side by side rather than having to figure out that they have to select another branch.  Do you want me to have a stab at re-organizing?

**Comment by AdvancedResearchConsulting** [comment]
Hi Nico,  Actually if you organize it as you describe I'll just follow your
convention moving forward, if it's not too much trouble. Better than me
attempting and mixing things up for you!
Austin

**Comment by nicost** [comment]
Sorry this took so insanely long Austin!  You should pester me more;).  

When you now checkout the main branch, there are 2 directories in the src folder, TriggerScope_V3 and Triggerscope_V4.  Let me know if this works for you!  If you stick to this layout, it will be easy to do PRs in the future to keep the projects in sync.

**Comment by AdvancedResearchConsulting** [comment]
This works thanks Nico!!

Austin Blanco
Advanced Research Consulting Corporation
e. ***@***.*** ***@***.***>
w. www.advancedresearch-consulting.com <http://www.advancedresearch-consulting.com/>
c. 510.708.2995
Send orders and invoices to: ***@***.*** ***@***.***>

**Pull request closed without merging**
